name: Build docker images
on: [push, pull_request]

jobs:
  # These jobs use Buildx layer caching
  docker_build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86-mingw32
          - platform: x64-mingw32
          - platform: x86-linux
          - platform: x86_64-linux
          - platform: x86_64-darwin
          - platform: arm64-darwin
          - platform: arm-linux
          - platform: aarch64-linux
          - platform: jruby

    runs-on: ubuntu-latest
    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: tmp/build-cache
          key: ${{ runner.os }}-${{ matrix.platform }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-buildx

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build docker image
        run: |
          docker buildx create --driver docker-container --use
          bundle exec rake build:${PLATFORM} RCD_DOCKER_BUILD="docker buildx build --cache-from=type=local,src=tmp/build-cache --cache-to=type=local,dest=tmp/build-cache-new --load"

      - name: Move build cache and remove outdated layers
        run: |
          rm -rf tmp/build-cache
          mv tmp/build-cache-new tmp/build-cache

      - name: Build rcd_test.gem
        run: |
          cd test/rcd_test/
          bundle install
          bundle exec rake gem:${PLATFORM}

      - name: Upload binary gem
        uses: actions/upload-artifact@v2
        with:
          name: gem-${{ matrix.platform }}
          path: test/rcd_test/pkg/*-*-*.gem

      - name: Upload source gem
        uses: actions/upload-artifact@v2
        if: matrix.platform == 'jruby'
        with:
          name: gem-ruby
          path: test/rcd_test/pkg/*-?.?.?.gem

      - name: Install rcd_test.gem
        if: matrix.platform != 'jruby'
        run: |
          cd test/rcd_test/
          bundle exec gem inst -l pkg/rcd_test-*-${PLATFORM}.gem

      - name: Test rcd_test.gem
        if: matrix.platform == 'x86_64-linux'
        run: |
          cd test/rcd_test/
          bundle exec rake test


  job_test_binary:
    name: Test
    needs: docker_build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            ruby: "3.0"
            platform: x64-mingw32
          - os: windows
            ruby: "2.3"
            platform: x64-mingw32
          - os: macos
            ruby: "3.0"
            platform: x86_64-darwin
          - os: macos
            ruby: "2.3"
            platform: x86_64-darwin
          - os: ubuntu
            ruby: "3.0"
            platform: x86_64-linux
          - os: ubuntu
            ruby: "2.3"
            platform: x86_64-linux
          - os: ubuntu
            ruby: jruby-head
            platform: jruby
          - os: ubuntu
            ruby: "3.0"
            platform: ruby

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Download gem from build job
        uses: actions/download-artifact@v2
        with:
          name: gem-${{ matrix.platform }}

      - run: gem install --local *.gem --verbose

      - name: Run tests
        run: |
          cd test/rcd_test/
          bundle install
          ruby -rrcd_test -S rake test
